### PR TITLE
Add sign-in page and PR template

### PR DESCRIPTION
**Pull request by tlwr**
What
----

- Adds PR template
- Adds sign-in (to PaaSmin) page and links to it from Hero

Screenshots
---

screencapture-localhost-9292-2019-05-06-22_06_05
*"sign in" link on home-page Hero; note: "Sign in" is not a nav link*

image
*`/sign-in` page (linked to from above)*

How to review
-------------

Code review

Spin it up locally

Who can review
--------------

Not @tlwr

### CODE REVIEW

**Comment by DebsDee** [comment]
@tlwr It would be good to have the 'sign in' link in the top nav so that it is available from other places on the product site.

**Comment by tlwr** [comment]
Adding the "Sign in" link wraps the navigation to the next line:

Screen Shot 2019-05-08 at 17 57 29

Is this okay?

Alternatively we could abbreviate "Platform as a Service" to "PaaS" :trollface:

**Comment by richardTowers** [comment]
:trollface: could fix the reflow issue by removing the Beta tag and going live

**Comment by DebsDee** [comment]
Alternatively, could wrap in fixed-width container

design-system-headers

**Comment by tlwr** [comment]
We have removed the Beta phase indicator because it is not necessary

Screen Shot 2019-05-10 at 09 26 59

**Comment by tlwr** [comment]
🎉 [Preview](https://tlwr-paas-product.cloudapps.digital/)

image

**Pull request merged**
